### ISSUE TITLE
failling tests

### ISSUE THREAD

**Issue by drebolo** [PerlDancer/dancer2-session-sereal#2]
dzil test  
[DZ] building distribution under .build/4hDOVTHMzd for installation
[DZ] beginning to build Dancer2-Session-Sereal
[@DAGOLDEN/Git::NextVersion] Bumping version from 0.001 to 0.002
[DZ] guessing dist's main_module is lib/Dancer2/Session/Sereal.pm
[DZ] extracting distribution abstract from lib/Dancer2/Session/Sereal.pm
[DZ] writing Dancer2-Session-Sereal in .build/4hDOVTHMzd
[@DAGOLDEN/CopyFilesFromBuild] Copied .build/4hDOVTHMzd/cpanfile to ./cpanfile
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Dancer2::Session::Sereal
Writing MYMETA.yml and MYMETA.json
cp lib/Dancer2/Session/Sereal.pm blib/lib/Dancer2/Session/Sereal.pm
Manifying blib/man3/Dancer2::Session::Sereal.3
PERL_DL_NONLAZY=1 /home/dinis/perl5/perlbrew/perls/perl-5.18.1/bin/perl "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef _Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/_.t
t/00-report-prereqs.t .. # 
# Versions for all modules listed in MYMETA.json (including optional ones):
# Version Module
# -------- -----------------------------------------
#2.133380 CPAN::Meta
#2.122 CPAN::Meta::Requirements
#0.11 Dancer2
#0.11 Dancer2::Core::Role::SessionFactory::File
#0.11 Dancer2::Core::Types
#5.006 Dist::Zilla
#0.059 Dist::Zilla::PluginBundle::DAGOLDEN
#6.84 ExtUtils::MakeMaker
#3.40 File::Spec
#3.40 File::Spec::Functions
#0.2304 File::Temp
#6.02 HTTP::Date
#1.34 IO::Handle
#1.13 IPC::Open3
#6.05 LWP::UserAgent
#1.35 List::Util
#1.003001 Moo
#0.100003 Pod::Coverage::TrustPod
#2.06 Sereal::Decoder
#2.06 Sereal::Encoder
#0.23 Test::CPAN::Meta
#1.001002 Test::More
#1.48 Test::Pod
#1.08 Test::Pod::Coverage
#2.01 Test::TCP
#0.84 YAML
#1.07 strict
#1.18 warnings

t/00-report-prereqs.t .. ok  
t/lifecycle.t .......... # Testing engine Sereal

> > Dancer2 v0.11 server 888 listening on http://0.0.0.0:50927
> > t/lifecycle.t .......... 1/? 
> > # Failed test 'session cookie set'
> > # at t/lifecycle.t line 53.
> > # undef
# Failed test 'correct cookie expired'
# at t/lifecycle.t line 86.
# got: 'UzP-s6eI8NwE--CXYhTLeIZX98LzE-4U'
# expected: undef
# Looks like you failed 2 tests of 27.

t/lifecycle.t .......... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/27 subtests 
## Test Summary Report

t/lifecycle.t        (Wstat: 512 Tests: 27 Failed: 2)
  Failed tests:  4, 15
  Non-zero exit status: 2
Files=2, Tests=28,  0 wallclock secs ( 0.03 usr  0.00 sys +  0.44 cusr  0.05 csys =  0.52 CPU)
Result: FAIL
Failed 1/2 test programs. 2/28 subtests failed.
make: **\* [test_dynamic] Error 2
error running make test

**Comment by yanick** [comment]
Tests are passing with the latest versions. Closing.
