### ISSUE TITLE
Storing objects in session not allowed

### ISSUE THREAD

**Issue by aka-raj** [PerlDancer/dancer2-session-sereal#3]
Trying to store a hashref with a DT object in session generates message: "Serializing objects using Sereal::Encoder was explicitly disabled using the 'croak_on_bless' option"

I see  D2::Session::Sereal sets croak_on_bless => 1 in its Sereal::Encoder->new constructor. Is this a feature? Can we at least have an override in say the engines/Session/Sereal config?

**Comment by yanick** [comment]
I think it is a case of "in 90% of the cases, you want to keep it simple and just send straight data structures". But I'm a fan of giving peeps enough rope to do whatever they want, so I just release a new version that allows you to change the encoder/decoder args via the configuration. Enjoy! :-)
